name: CI Class

on:
   push:
     branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install

    
    #- name: Instalar angular
    #  run: npm install -g @angular/cli@15

    #- name: Instalar angular/material
    #  run: npm install @angular/material

    #- name: Instalar json
    #  run: npm install -g json-server

    - name: Executar testes
      run: npm test -- --include=CinemaList/src